"use client";

import { useEffect, useState } from "react";

type Status = { scheduler_enabled: boolean; collection_enabled: boolean; client_mode: string; enabled_sources: string[]; sources: { source: string; last_success_at: string | null; next_due_at: string | null; last_error: string | null }[] };
type Statistics = { traffic: { route_no: string | null; direction: string | null; observations: number; average_speed: number | null }[]; incidents: { route_no: string | null; incidents: number }[]; fuel_prices: { product_code: string; stations: number; average_price: number | null }[] };
type Payload = { status: Status; statistics: Statistics; incidents: { items: unknown[] } };

function moment(value: string | null) { return value ? new Intl.DateTimeFormat("ko-KR", { dateStyle: "short", timeStyle: "short", timeZone: "Asia/Seoul" }).format(new Date(value)) : "없음"; }
function number(value: number | null) { return value === null ? "-" : new Intl.NumberFormat("ko-KR", { maximumFractionDigits: 1 }).format(value); }

export function TransportDashboard() {
  const [payload, setPayload] = useState<Payload | null>(null); const [error, setError] = useState("");
  useEffect(() => { let active = true; Promise.all([fetch("/api/transport/transport/collector-status"), fetch("/api/transport/transport/statistics?days=7"), fetch("/api/transport/transport/highways/incidents?days=1&limit=20")]).then(async ([status, statistics, incidents]) => { if (![status, statistics, incidents].every((response) => response.ok)) throw new Error("일부 transport API가 응답하지 않았습니다."); const [statusData, statisticData, incidentData] = await Promise.all([status.json(), statistics.json(), incidents.json()]); if (active) setPayload({ status: statusData, statistics: statisticData, incidents: incidentData }); }).catch((reason) => active && setError(reason instanceof Error ? reason.message : "현황을 불러오지 못했습니다.")); return () => { active = false; }; }, []);
  if (error) return <p className="error">{error}</p>; if (!payload) return <p className="loading">저장된 교통정보 현황을 읽는 중입니다…</p>;
  return <div className="grid"><section className="panel"><span className="metric">Dagster scheduler</span><strong className="value">{payload.status.scheduler_enabled ? "활성" : "중지"}</strong><p className="quiet">수집 {payload.status.collection_enabled ? "허용" : "비활성"} · {payload.status.client_mode}</p></section><section className="panel"><span className="metric">활성 provider</span><strong className="value">{payload.status.enabled_sources.length}</strong><p className="quiet">{payload.status.enabled_sources.join(", ") || "없음"}</p></section><section className="panel"><span className="metric">최근 24시간 돌발</span><strong className="value">{payload.incidents.items.length}</strong><p className="quiet">저장된 고속도로 돌발 기준</p></section><section className="panel wide"><h2>수집 소스</h2><ul className="status-list">{payload.status.sources.map((source) => <li key={source.source}><span><strong>{source.source}</strong>{source.last_error ? <small className="error"> · {source.last_error}</small> : null}</span><span className="quiet">성공 {moment(source.last_success_at)} · 다음 {moment(source.next_due_at)}</span></li>)}</ul></section><section className="panel"><h2>유가 통계 (7일)</h2><ul className="row-list">{payload.statistics.fuel_prices.map((item) => <li key={item.product_code}><span>{item.product_code} · {item.stations}개</span><strong>{item.average_price === null ? "-" : `${number(item.average_price)}원`}</strong></li>)}</ul></section><section className="panel wide"><h2>고속도로 속도 (7일)</h2><ul className="row-list">{payload.statistics.traffic.slice(0, 8).map((item, index) => <li key={`${item.route_no}-${item.direction}-${index}`}><span>{item.route_no ?? "노선 미상"} {item.direction ?? ""} · {item.observations}건</span><strong>{item.average_speed === null ? "-" : `${number(item.average_speed)} km/h`}</strong></li>)}</ul></section><section className="panel"><h2>노선별 돌발</h2><ul className="row-list">{payload.statistics.incidents.slice(0, 8).map((item, index) => <li key={`${item.route_no}-${index}`}><span>{item.route_no ?? "노선 미상"}</span><strong>{item.incidents}건</strong></li>)}</ul></section></div>;
}
